### ISSUE TITLE
Feedback for “Getting Started with the BigCommerce REST API”

### ISSUE THREAD

**Issue by dhurley12** [bigcommerce/dev-docs#1854]
I hate the new docs!!!!! Where is the testing ability? Where are the examples? WTF?!?!? this sucks

**Comment by slsriehl** [comment]
@dhurley12 -- Thank you for your frankness. We've continued to iterate on the Developer Center and have more plans to improve the developer experience in the works. 

If you have more feedback in the future, direct it to https://github.com/bigcommerce/docs/issues. Although we are happy to receive critical feedback, we ask that your input align with our [code of conduct](https://github.com/bigcommerce/docs?tab=coc-ov-file) so that we can engage constructively and better address the meat of your issues.

**Comment by dhurley12** [comment]
9-10 months have gone by. Keep up!!!
